### ISSUE TITLE
Setup translation

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-next#15]
Setup translation which best matches our implementation of client side translation of current site with a language switcher.

The solution should provide ways to extract messages from the code and update the translations though CLI

There are multiple options, evaluate and choose:

https://github.com/vercel/next.js/tree/canary/examples/i18n-routing
https://github.com/vercel/next.js/tree/canary/examples/with-i18n-rosetta
https://github.com/vercel/next.js/tree/canary/examples/with-next-i18next
https://github.com/vercel/next.js/tree/canary/examples/with-lingui
https://github.com/vercel/next.js/tree/canary/examples/with-next-translate

**Comment by mdPial** [comment]
I am working on that issue.

**Comment by mdPial** [comment]
> and update the translations though CLI

Did you intend to update the translations of UI through CLI?.

**Comment by codedsun** [comment]
@mdPial Are you working on this?

**Comment by mdPial** [comment]
I have stopped in the middle. I wanted to clear my doubts. If you want to work you can start. I am preparing for exam right now so may b I won't be able to work on this issue for few days.

**Comment by iamdevvalecha** [comment]
starting working on this.

**Comment by iamdevvalecha** [comment]
starting this.

**Comment by iamareebjamal** [comment]
From chat:

Best is to test their examples. Most focus of server side routing technique to switch language. What we need is a client side switcher with ability to extract messages through CLI. Lingui is very close to our current solution but it depends on msgmerge which the current project also depends upon. So, I would prefer a pure JS solution, but if they don't fit our criteria, we can go with lingui. Also, I don't know if lingui supports CLI message extraction or not

**Comment by iamareebjamal** [comment]
Best is to test their examples. Most focus of server side routing technique to switch language. What we need is a client side switcher with ability to extract messages through CLI. Lingui is very close to our current solution but it depends on msgmerge which the current project also depends upon. So, I would prefer a pure JS solution, but if they don't fit our criteria, we can go with lingui.
