### ISSUE TITLE
Setup locale autodetection 

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-next#31]
Setup lingui locale detection with default, storage and URL (lang query) method. Make sure language switcher persists the changes across reloads.

Also, make sure the storage key is compatible with ember site so that it picks up any change in locale from localstorage and vice versa

**Comment by takshch** [comment]
I am working on this issue!

**Comment by iamareebjamal** [comment]
@takshch Status?

**Comment by takshch** [comment]
@iamareebjamal I have setup open-event-next and now doing my research on Lingui.
