### ISSUE TITLE
Setup dayjs with timezone and locale plugins

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-next#32]
We'll be using dayjs instead of moment in the project.
Setup the project with example date and a timezone switcher. 

1. Date should be parsed as ISO8601 string and shown in two timezones: local and SGT. 
2. And a select element with timezone switcher should be added to demonstrate second date changing time on changing the timezone while local timezone date remains same
3. The formatted date should follow the locale selected as current. Meaning AM/PM 12hr/24hr rules, day names like Thursday, etc should be according to the selected locale
4. Locales must be loaded dynamically, on demand and not be bundled with main bundle

**Comment by iamareebjamal** [comment]
If dayjs or its plugins cannot fulfill the criteria, suggest some other small treeshakable library or create your own methods using native JS Intl API

**Comment by iamdevvalecha** [comment]
i am starting working on this issue. please don't make any PR.

**Comment by iamareebjamal** [comment]
@iamdevvalecha Status?

**Comment by iamdevvalecha** [comment]
@iamareebjamal dependencies installed with locale plugins.
i have some questions regarding this issue. i will ask in eventyay meeting.

**Comment by iamareebjamal** [comment]
@pc-beast Please take this up

**Comment by pc-beast** [comment]
sure

**Comment by pc-beast** [comment]
sure

**Comment by takshch** [comment]
@iamareebjamal Please watch the video and let me know if there is need to change.
https://user-images.githubusercontent.com/26649558/115474877-12246c80-a25c-11eb-9298-cca9f26a005b.mp4

**Comment by iamareebjamal** [comment]
Changing language to hindi should change the dates to hindi as well

**Comment by pc-beast** [comment]
@takshch are you working on it?

**Comment by codedsun** [comment]
We have to import every locale in dayjs if we want to convert the date locale-specific @iamareebjamal @mariobehling

**Comment by takshch** [comment]
@codedsun Even after doing that it will not change the current displayed date. Simply, it means it is not gonna rerender the dates with new locale.

**Comment by takshch** [comment]
@pc-beast You can take this issue if you want. Also, I would suggest that it is better to use any library because our own solution will produce errors and will not be testable as that of library.

**Comment by codedsun** [comment]
@takshch I think it's mentioned in the doc so it will work, but the way is not better as you have to import every supporting locale of your site.

**Comment by codedsun** [comment]
@pc-beast Any other solution you would like to mention?

**Comment by takshch** [comment]
> @takshch I think it's mentioned in the doc so it will work, but the way is not better as you have to import every supporting locale of your site.

We can also use dynamic import if our setup supports it but still it changing locale will not change displayed date.
Every time we change the locale, then we need to publish that your locale is changed, to every subscriber.
If you don't know  about `pubsub` pattern, then please learn it.

**Comment by pc-beast** [comment]
> @pc-beast Any other solution you would like to mention?
Sorry for replying late.
yes, I think we can use days js. but it requires making one function. I found this while I was exploring it. please refer this-
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
