### ISSUE TITLE
Setup MUI alerts as reusable components for displaying error and success messages

### ISSUE THREAD

**Issue by pc-beast** [fossasia/open-event-next#326]
As of now if errors occur in fetching data, the message is not displayed to the user. Similarly, success messages also need to be displayed to users. Implement it in the same way as in the ```emberjs``` but using MUI alerts or similar components.
![image](https://user-images.githubusercontent.com/56963647/155832948-324f8d3c-0ccf-492b-be2f-bf0b17f8c05e.png)

**Comment by Dnouv** [comment]
Hello @pc-beast 
I would like to work on this issue. If it's still available, please let me know.
Thank you!

**Comment by pc-beast** [comment]
There is already an open PR by me. As I am busy with other things right now you are free to take over the existing changes in a new PR and complete it. Thanks. @Dnouv
