### ISSUE TITLE
Getting this error on localhost:3000

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-next#41]
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/20026440/115593317-fe2b4a00-a2f1-11eb-8d7a-9d068619d6a9.png">

**Comment by iamareebjamal** [comment]
Run npm run compile first

**Comment by takshch** [comment]
@iamareebjamal I also faced this error after pulling from upstream. Even after `npm run compile`, development server still showing the same error.

**Comment by iamareebjamal** [comment]
Checking

**Comment by pc-beast** [comment]
It seems that there is some mistake in logic used for locale detection. Error is produced when there is no cookie for locale.

**Comment by pc-beast** [comment]
![Screenshot from 2021-04-22 11-15-02](https://user-images.githubusercontent.com/56963647/115662124-2485cf80-a35c-11eb-969c-c7eb12c564d0.png)
This is in production. :(

**Comment by Ayush2020012016** [comment]
I also get this error but after some time it get corrected by itself

**Comment by Ayush2020012016** [comment]
can you tell how to debug such error

**Comment by pc-beast** [comment]
It will be fixed once #42 gets merged.
